config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import view

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path("charge", view.charge, name='charge'),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("contact_table.users.urls", namespace="users"),
    ),
    path(
        "contacts/",
        include("contacts.urls", namespace="contacts"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

contact_table/users/urls.py
from django.urls import path

from contact_table.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

contacts/urls.py
from django.urls import path, re_path
from . import views


app_name = "contacts"
urlpatterns = [
    path("", views.ContactsPageView.as_view() , name= "contacts" ),
    path("?page=n", views.ContactsPageView.as_view(), name= "contacts"),
    path("~create/", views.ViewCreatePost.as_view(), name="create"),
    re_path(r"^update/(?P<pk>\d+)/$", views.ViewUpdatePost.as_view(), name="update"),
    re_path(r"^delete/(?P<pk>\d+)/$", views.ViewDeletePost.as_view(), name="delete")
]

contact_table/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

contacts/models.py
from django.db import models
from django.contrib.auth.models import User


class Contact(models.Model):
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    customer_email = models.EmailField(blank=False, null=False)
    customer_number = models.CharField(max_length=16)
    user = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='contacts')

    def __str__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    class Meta:
        unique_together = (("user", "customer_number"), ("user", "customer_email"))

contact_table/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

contacts/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ContactForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'customer_email', 'customer_number')

    def clean(self):
        clean_data = super(ContactForm, self).clean()
        customer_email = clean_data.get('customer_email')
        customer_number = clean_data.get('customer_number')

        if Contact.objects.filter(customer_email=customer_email, user=self.request.user).exists():
            msg = u'This email already exsist.'
            self._errors['customer_email'] = self.error_class([msg])

        if Contact.objects.filter(customer_number=customer_number, user=self.request.user).exists():
            msg = u'This number already exsist.'
            self._errors['customer_number'] = self.error_class([msg])
        return clean_data

contact_table/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

contacts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Contact
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from .forms import ContactForm
from .form_for_update import ContactUpdateForm
from django.core.paginator import Paginator
from django.shortcuts import render



class ContactsPageView(LoginRequiredMixin, ListView):
    template_name = 'account/contacts.html'
    context_object_name = "contacts_list"
    paginate_by = 5

    def get_queryset(self):
        queryset = self.request.user.contacts.all()
        return queryset


class ViewCreatePost(LoginRequiredMixin, CreateView):
    template_name = 'account/create.html'
    form_class = ContactForm
    success_url = reverse_lazy('contacts:contacts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ViewCreatePost, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ViewCreatePost, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class ViewUpdatePost(LoginRequiredMixin, UpdateView):
    model = Contact
    template_name = 'account/update.html'
    form_class = ContactUpdateForm
    success_url = reverse_lazy('contacts:contacts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ViewUpdatePost, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ViewUpdatePost, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class ViewDeletePost(LoginRequiredMixin, DeleteView):
    template_name = 'account/delete.html'
    model = Contact
    success_url = reverse_lazy('contacts:contacts')

contact_table/templates/1551974522936.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

<style>
.pricingTable{
 box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
 padding: 50px 15px;
 text-align: center;
 margin-top: 40px;
 color: #292929;
 perspective: 700px;
 z-index: 1;
 position: relative;
 transition: all 0.3s ease-in-out 0s;
}
.pricingTable:hover{ color: #fff; }
.pricingTable:after{
 content: "";
 width: 100%;
 height: 100%;
 background: #3485ef;
 position: absolute;
 top: 0;
 left: 0;
 opacity: 0;
 z-index: -1;
 transform: rotateY(70deg);
 transition: all 0.3s ease-in-out 0s;
}
.pricingTable:hover:after{
 opacity: 1;
 transform: rotateY(0deg);
}
.pricingTable .icon{
 width: 69px;
 height: 69px;
 line-height: 69px;
 border-radius: 50%;
 background: #fff;
 box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
 margin: 0 auto;
 font-size: 25px;
 color: #3485ef;
 position: absolute;
 top: -34px;
 left: 0;
 right: 0;
}
.pricingTable .pricingTable-header{
 margin-bottom: 30px;
}
.pricingTable .title{
 display: block;
 font-size: 18px;
 font-weight: 600;
 text-transform: uppercase;
 margin: 0 0 10px 0;
}
.pricingTable .price-value{
 display: inline-block;
 border-bottom: 5px solid #3485ef;
 font-size: 30px;
 font-weight: 700;
 transition: all 0.3s ease-in-out 0s;
}
.pricingTable:hover .price-value{
 border-bottom-color: #fff;
}
.pricingTable .pricing-content{
 list-style: none;
 padding: 0;
 margin: 0 0 20px 0;
}
.pricingTable .pricing-content li{
 font-size: 14px;
 line-height: 40px;
}
.pricingTable .pricingTable-signup{
 display: inline-block;
 padding: 9px 23px;
 background: #3485ef;
 font-size: 14px;
 font-weight: 600;
 color: #fff;
 text-transform: uppercase;
 position: relative;
 transition: all 0.25s ease-in-out 0s;
}
.pricingTable:hover .pricingTable-signup{
 background: #fff;
 color: #3485ef;
}
.pricingTable .pricingTable-signup:before,
.pricingTable .pricingTable-signup:after{
 content: "";
 height: 100%;
 position: absolute;
 top: 0;
 border-top: 18px solid transparent;
 border-bottom: 18px solid transparent;
 transition: all 0.25s ease-in-out 0s;
}
.pricingTable .pricingTable-signup:before{
 left: -12px;
 border-right: 12px solid #3485ef;
}
.pricingTable .pricingTable-signup:after{
 right: -12px;
 border-left: 12px solid #3485ef;
}
.pricingTable:hover .pricingTable-signup:before{
 border-right-color: #fff;
}
.pricingTable:hover .pricingTable-signup:after{
 border-left-color: #fff;
}
@media only screen and (max-width: 990px){
 .pricingTable{ margin-bottom: 30px; }
}
@media only screen and (max-width: 767px){
 .pricingTable{ margin-bottom: 50px; }
}
</style>

<div class="container">
<div class="row ">

 <div class="col-md-4 col-sm-6">
 <div class="pricingTable">
 <span class="icon"><i class="fa fa-globe"></i></span>
 <div class="pricingTable-header">
 <h3 class="title">Standard</h3>
 <span class="price-value">$10</span>
 </div>
 <ul class="pricing-content">
 <li>50GB Disk Space</li>
 <li>50 Email Accounts</li>
 <li>50GB Monthly Bandwidth</li>
 <li>10 Subdomains</li>
 <li>15 Domains</li>
 </ul>
 <a href="#" class="pricingTable-signup">Sign Up</a>
 </div>
 </div>

 <div class="col-md-4 col-sm-6">
 <div class="pricingTable">
 <span class="icon"><i class="fa fa-briefcase"></i></span>
 <div class="pricingTable-header">
 <h3 class="title">Business</h3>
 <span class="price-value">$20</span>
 </div>
 <ul class="pricing-content">
 <li>60GB Disk Space</li>
 <li>60 Email Accounts</li>
 <li>60GB Monthly Bandwidth</li>
 <li>15 Subdomains</li>
 <li>20 Domains</li>
 </ul>
 <a href="#" class="pricingTable-signup">Sign Up</a>
 </div>
 </div>

 <div class="col-md-4 col-sm-6">
 <div class="pricingTable">
 <span class="icon"><i class="fa fa-diamond"></i></span>
 <div class="pricingTable-header">
 <h3 class="title">Premium</h3>
 <span class="price-value">$30</span>
 </div>
 <ul class="pricing-content">
 <li>70GB Disk Space</li>
 <li>70 Email Accounts</li>
 <li>70GB Monthly Bandwidth</li>
 <li>20 Subdomains</li>
 <li>25 Domains</li>
 </ul>
 <a href="#" class="pricingTable-signup">Sign Up</a>
 </div>
 </div>

</div><!-- ./row -->
</div><!-- ./container -->

contact_table/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

contact_table/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}contact_table{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">contact_table</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'contacts:contacts' %}">{% trans "Contacts" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

contact_table/templates/pages/about.html
{% extends "base.html" %}

contact_table/templates/pages/charge.html
{% extends base.html %}

contact_table/templates/pages/home.html
{% extends "base.html" %}

contact_table/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

contact_table/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

contact_table/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}